# TensorFlow Tutorial #02

# Convolutional Neural Network

Convolutional Networks work by moving small filters across the input image. This means the filters are re-used for recognizing patterns throughout the entire input image. This makes the Convolutional Networks much more powerful than Fully-Connected networks with the same number of variables. This in turn makes the Convolutional Networks faster to train.

## Flowchart

![](images/02_network_flowchart.png)

This input image is processed in the first convolutional layer using the filter-weights. This results in 16 new images, one for each filter in the convolutional layer. The images are also down-sampled so the image resolution is decreased from 28x28 to 14x14.

These 16 smaller images are then processed in the second convolutional layer. We need to filter-weights for each of these 16 channels, and we need filter-weights for each output channel of this layer. There are 36 output channels so there are a total of 16 x 36 = 576 filters in the second convolutional layer. The resulting images are down-samples again to 7x7

The output of the second convolutional layer is 36 images of 7x7 pixels each. These are then flattened to a single vector of length 7 x 7 x 36 = 1764, which is used as the input to fully-connected layer with 128 neurons (or elements). This feeds into another fully-connected layer with 10 neurons. one for each of classes, which is used to determine the class of the image, that is, which number is depiced in the image.

The convolutional filters are initially chosen at random, so the classification is done randomly. The error between the predicted and true class of the input image is measured as the so-called cross-entropy. The optimizer then automatically propagates this error back through the Convolutional Network using the chain-rule of differentiation and updates the filter-weights so as to improve the classification error. This is done iteratively thousands of times until the classification error is sufficiently low.

In [1]:
import numpy as np

In [11]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [10]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b.shape

(3, 3)

In [12]:
np.matmul(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [7]:
a.dot(b).shape

(2, 2)

In [13]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [14]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])